policies:
  - type: commit
    spec:
      dco: true
      gpg:
        required: true
      header:
        length: 90
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      conventional:
        types: ["feat", "fix", "build", "chore", "ci", "docs", "perf", "refactor", "revert", "style", "test", "release"]
        scopes: [".*"]
