# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0
settings:
  +@xmlns: http://maven.apache.org/SETTINGS/1.0.0
  +@xmlns:xsi: http://www.w3.org/2001/XMLSchema-instance
  +@xsi:schemaLocation: |-
    http://maven.apache.org/SETTINGS/1.0.0
    https://maven.apache.org/xsd/settings-1.0.0.xsd
